return {
  -- "olimorris/codecompanion.nvim",
  -- dependencies = {
  --   "nvim-lua/plenary.nvim",
  --   "nvim-treesitter/nvim-treesitter",
  --   "j-hui/fidget.nvim"
  -- },
  -- opts = {
  --   strategies = {
  --     chat = {
  --       adapter = "openai",
  --     },
  --     inline = {
  --       adapter = "openai",
  --     },
  --   },
  --   adapters = {
  --     openai = function()
  --       return require("codecompanion.adapters").extend("openai", {
  --         env = {
  --           api_key = "OPENAI_API_KEY",
  --         },
  --       })
  --     end,
  --   },
  --   display = {
  --     diff = {
  --       enabled = true,
  --       close_chat_at = 240, -- Close an open chat buffer if the total columns of your display are less than...
  --       layout = "vertical", -- vertical|horizontal split for default provider
  --       opts = { "internal", "filler", "closeoff", "algorithm:patience", "followwrap", "linematch:120" },
  --       provider = "default", -- default|mini_diff
  --     },
  --   },
  --   chat = {
  --     roles = {
  --       ---The header name for the LLM's messages
  --       ---@type string|fun(adapter: CodeCompanion.Adapter): string
  --       llm = function(adapter)
  --         return "CodeCompanion (" .. adapter.formatted_name .. ")"
  --       end,
  --
  --       ---The header name for your messages
  --       ---@type string
  --       user = "Me",
  --     }
  --   }
  -- },
  -- init = function()
  --   require("plugins.codecompanion.fidget-spinner"):init()
  -- end,
};
